### ISSUE TITLE
Add use case: Migrate my blog comments from Disqus to Github Issues

### ISSUE THREAD

**Issue by lazywinadmin** [microsoft/PowerShellForGitHub#102]
Not sure if you would be interested to add this into your Readme examples/use cases. 
I used your module to migrate all my disqus blog comments to Github issues. It is using Utterances-Bot to create new issues and display existing comments. 

This is how i found the issue fixed by my PR #76 
Thanks for this tool, I'll continue to contribute if i see other bugs.

Here is my blog post where i talked about it: https://lazywinadmin.com/2019/04/moving_blog_comments.html

**Comment by HowardWolosky** [comment]
Thanks @lazywinadmin -- It's great to see how helpful the module was for you.  That's a very detailed/well-written article as well.  If you'd like to create a PR to add an update to `USAGE.md` that references your blog post as a more advanced example, I'd approve it.

One thing I did notice in there is that you disabled telemetry as part of your script execution.  That's _totally fine_ -- that configuration option is there to provide each user that choice.  I'm simply curious _why_ you made that choice -- do you generally disable telemetry for all the products that you use, or did you do it for this tool specifically for some other reason?  I ask, because if there's a way to _improve_ the telemetry in this project so that users don't feel a need to disable it, that will result in an overall net postive.

The telemetry is helpful for knowing that there are people out there, using it.  There's certainly more motiviation for continued maintenance and improvement of the project when there's a way to measure its audience.

**Comment by lazywinadmin** [comment]
Thank you

I agree with the telemetry approach and I'm not against it.
I think i turned it off because the first time i ran `New-GithubIssue` it took more than 20 seconds to add the issue. So i just disabled it since I had to create many issues and comments for my blog comment migration.

I just retested..  I did not realize that the 20 seconds seem to be only for the first call.
Other issues are created under 1/2 seconds.

Here is a screenshot of that first issue creation (it took +20sec)
![image](https://user-images.githubusercontent.com/3020909/55931562-e2591d80-5bda-11e9-9e72-40ebeca45398.png)

**Comment by HowardWolosky** [comment]
Thanks @lazywinadmin.  That first-run experience is currently expected, as the first-run experience downloads 3 NuGet packages to get the necessary binaries to submit the telemetry through Application Insights.  It then caches them for that PowerShell session, and tells you how to permanently cache them (by storing them in your module directory OR a directory of your choice and then setting the `AssemblyPath` configuration value).

I've created #104 to track a feature to remove that requirement entirely by reverse-engineering the web request that the dll's use to communicate with Application Insights.

But yes, that _is_ an unfortunate first-run experience in order for telemetry to work.
