### ISSUE TITLE
Typo in Update-GitHubRepository variable

### ISSUE THREAD

**Issue by amis92** [microsoft/PowerShellForGitHub#136]
A typo results in an incorrect URL being built. Because the variable is misspelled, the repository name is not appended to the URL.

https://github.com/microsoft/PowerShellForGitHub/blob/9bdb37c053f98f108d346050622b609d8488fd45/GitHubRepositories.ps1#L616

Fix:
```diff
- 'UriFragment' = "repos/$OwnerName/$ReposistoryName"
+ 'UriFragment' = "repos/$OwnerName/$RepositoryName"
```

**Comment by HowardWolosky** [comment]
Once again, great catch @amis92.

This was the only occurrence of this specific typo throughout the project.

I believe these errors you've found to be fairly abnormal errors relative to the rest of the project, and definitely should have been caught by proper tests.  I'll get a separate issue opened to increase the testing for this file.

Fixed by #137
