### ISSUE TITLE
Cannot bind parameter 'Uri'. Cannot convert value "https://DisableLogging:False/api/v3/user" to type "System.Uri". Error: "Invalid URI: Invalid port specified."

### ISSUE THREAD

**Issue by damienvanrobaeys** [microsoft/PowerShellForGitHub#156]
Hello,

I was testing the module without any issue.

I played with the set-githubconfiguration disablelogging and disabletelemetry.

Now when I try to use the module I have the below error:
Cannot bind parameter 'Uri'. Cannot convert value "https://DisableLogging:False/api/v3/user" to type "System.Uri". Error: "Invalid URI: Invalid port specified."

I was using the below command:
(Get-GitHubUser -Current).login

I tried to uninstall the module then install it again and still same issue.
I can't use the module anymore.

I tested on another computer with the same token and that worked.

![image](https://user-images.githubusercontent.com/8832278/79747116-6d4f1680-830b-11ea-9270-4d2ab26eda94.png)

**Comment by damienvanrobaeys** [comment]
I have now the same issue  on my other computer after testing to set the disabletelemetry to false
Set-GitHubConfiguration -DisableTelemetry:$False

**Comment by damienvanrobaeys** [comment]
I just resolved my issue by reseting config
Reset-GitHubConfiguration

**Comment by HowardWolosky** [comment]
That would have just removed the setting.  I need to investigate to see what might be going on wrong when that setting is being used.  Keeping this open for investigation.

**Comment by HowardWolosky** [comment]
@damienvanrobaeys - I have been unable to reproduce what you showed.  If you have a log of your commands from _before_ you disabled logging (and then got into this state), it would be helpful.  If there's a real problem here, I'd love to get it fixed.  User error should not have been possible due to the strongly-typed getters/setters for modifying the configuration of the module, and yet it looks like something went wrong.

**Comment by HowardWolosky** [comment]
The only thing I can think of is if you had done something like this:

```
Set-GitHubConfiguration -ApiHostName DisableTelemetry:false
```
