### ISSUE TITLE
Get-GitHubRepository doesnt show private repository.

### ISSUE THREAD

**Issue by Alex-0293** [microsoft/PowerShellForGitHub#178]
Hello,
I want to get all my repository.
`Get-GitHubRepository -Visibility All -Type All -OwnerName "Alex-0293"`
This show only public repository, instead of all.
But i can see my private repository with
`Get-GitHubRepository -Visibility All -Type All -OwnerName "Alex-0293" -RepositoryName "GitProjectClone"`.

**Comment by HowardWolosky** [comment]
You want to call:
```powershell
Get-GitHubRepository -Visibility All
```
(without `OwnerName`). Per the [API documentation](https://developer.github.com/v3/repos/#list-repositories-for-the-authenticated-user), the only API where you can specify `Visibility` is for the current authenticated user (thus, you don't specify `UserName`).  Additionally, if you use that API, you can't specify _both_ `Visibility` _and_ `Type` in the same request.  Doing so will result in a `422`.

Looks like `Get-GitHubRepository` needs to be cleaned up a bit (either with better ParameterSets or internal error checking) to prevent usage like yours above.

Thanks for calling attention to this.

**Comment by HowardWolosky** [comment]
To be clear, when you called the API like this: `Get-GitHubRepository -Visibility All -Type All -OwnerName "Alex-0293"`, you were _actually_ calling [this API](https://developer.github.com/v3/repos/#list-repositories-for-a-user) which can _only_ display public repositories.  You can verify this for yourself by either looking at your `PowerShellForGitHub.log` file, or by calling it again and specifying `-Verbose` as part of the request.

**Comment by Alex-0293** [comment]
May be i dont understand, but i have the same results.
`Get-GitHubRepository -Visibility All -verbose`

> VERBOSE: [0.13.1] Executing: Get-GitHubRepository -Visibility "All" -Verbose:$true
VERBOSE: Getting repos for Alex-0293
VERBOSE: Accessing [Get] https://api.github.com/users/Alex-0293/repos?visibility=all [Timeout = 0)]
VERBOSE: Telemetry has been disabled via configuration. Skipping reporting event [Get-GitHubRepository].

`Get-GitHubRepository -Visibility All -OwnerName "Alex-0293" -verbose`

> VERBOSE: [0.13.1] Executing: Get-GitHubRepository -Visibility "All" -OwnerName "Alex-0293" -Verbose:$true
VERBOSE: Getting repos for Alex-0293
VERBOSE: Accessing [Get] https://api.github.com/users/Alex-0293/repos?visibility=all [Timeout = 0)]
VERBOSE: Telemetry has been disabled via configuration. Skipping reporting event [Get-GitHubRepository].

**Comment by HowardWolosky** [comment]
My guess is you configured a default owner name.
What does this return:
`Get-GitHubConfiguration -Name DefaultOwnerName`?
If you configured that, then it's pre-filling in `OwnerName`, and thus it has the same result.

**Comment by Alex-0293** [comment]
Thank you! 
You are absolutely right.
Now its work as expected.

**Comment by HowardWolosky** [comment]
Leaving this open, because the function should not have permitted that combination of parameters without an error.  Should have a fix out soon.

**Comment by jbostoen** [comment]
Using v15.0.1 of this module; calling 

`Get-GitHubRepository -Visibility All`

Still only shows my public repositories and not the private ones.
What am I missing? Is configuration required?

I tried adding default owner name; which seems to be correct if I try `Get-GitHubConfiguration -Name DefaultOwnerName `

**Comment by HowardWolosky** [comment]
@jbostoen - You posted an additional comment to this Issue this morning, reporting that the problem wasn't resolved for you, but then you deleted the comment.  Presumably you figured out the problem.  However, it would be helpful to keep that in here in case others come across the same problem and want to know what the solution was.

This was your original comment:

>Using v15.0.1 of this module; calling
> `Get-GitHubRepository -Visibility All`
> Still only shows my public repositories and not the private ones.
> What am I missing? Is configuration required?
> I tried adding default owner name; which seems to be correct if I try `Get-GitHubConfiguration -Name DefaultOwnerName`

_Configuration_ is _not_ required.  In fact, even if you were to specify a default owner name, it would not be used.
You can't query for private repositories of _other_ users.  By the very nature of them being private, you can only query for them if they are _yours_.  That's why the `Visibility` parameter for `Get-GitHubRepository` doesn't work when a `UserName` has been specified...  It's a parameter that only works against the current authenticated user account.

So, while _configuration_ isn't required, **authentication** _is_.  If it wasn't working for you, it's most likely because you had not yet authenticated with GitHub via `Set-GitHubAuthentication`.

**Comment by jbostoen** [comment]
Hi

Sorry for the inconvenience, it turned out not all privileges were linked to the access token.

Met vriendelijke groeten
Jeffrey Bostoen
Informaticus
T +32 51 337 247
Stad Izegem
Korenmarkt 10
B-8870 Izegem
www.izegem.be<http://www.izegem.be>
[cid:image004.png@01D6AC39.935D0AB0]
[cid:image005.png@01D6AC39.935D0AB0]
Elke e-mail uitgaande van Stad, OCMW en/of Zorg Izegem of van een van haar medewerkers heeft uitsluitend een informatieve waarde en kan geen verbintenissen tot stand brengen.
Verbintenissen kunnen enkel tot stand worden gebracht via de klassieke briefwisseling, ondertekend door de algemeen directeur en in het geval van stad of OCMW ook de burgemeester.
Lees onze privacyverklaring<https://privacy.izegem.be>.
