### ISSUE TITLE
Investigate UT failures happening on Linux/mac in CI build

### ISSUE THREAD

**Issue by HowardWolosky** [microsoft/PowerShellForGitHub#198]
We have recently disabled UT's for Linux and Mac in the CI build because there have been unexpected failures during execution that don't appear to happen when run locally (at least for Linux).  I'd like to get those re-enabled for full coverage, but they've been disabled in the short term to ensure that we can get real value out of the CI build since Windows is running cleanly right now.

**Comment by X-Guardian** [comment]
The `GitHubAnalytics`, `Obtaining issues for repository`, `When initially created, there are no issues` test error is caused by the difference with PowerShell 5 vs 7 dealing with the empty array return value from `Get-GitHubIssue`.

For this code specifiying the URI of a newly created repo (without issues):

```powershell
$issues = Get-GitHubIssue -Uri $Uri
@($issues).count
```

PowerShell 5 will return 0, but PowerShell 7 will return 1.

I suggest removing the array sub-expression operator around `$issues` in the test, and in the `GitHubCore` `Invoke-GHRestMethodMultipleResult` function, use the [comma operator](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_operators?view=powershell-7#comma-operator-) to create the return array.

**Comment by X-Guardian** [comment]
If you want to be consistent and run the unit tests on PowerShell 7 for Windows, Linux and Mac, change your `powershell` tasks in `run-unitTests.yaml` to `pwsh` tasks.

**Comment by HowardWolosky** [comment]
Thanks so much @X-Guardian!  It hadn't occurred to me that the difference was due to PoSh 7 vs <7.  I've been able to repro the UT failures on my Windows machine with PoSh 7 and I'm now making the fixes.  That difference in behavior between array handling in 7 is quite interesting.

I don't want to switch the CI to only using `pwsh` tasks, because internally we have a system that's running PoSh 4.x that depends on this module (hence the min requirement in the module manifest).  I like the (unintentional) outcome that the different platforms are thus testing the module against different versions of the runtime.

Again -- thanks for taking the time to investigate and respond!
