### ISSUE TITLE
Implement `-PassThru` for all `Set-*` cmdlets

### ISSUE THREAD

**Issue by TylerLeonhardt** [microsoft/PowerShellForGitHub#217]
#### Feature Idea Summary

It's usually good practice for `Set-*` cmdlets to output nothing and then offer a `-PassThru` to output the result.

This allows output to not be as noisy and so that you don't have to pipe to `Out-Null`

#### Feature Idea Additional Details

All this would mean is:

* Adding a `-PassThru` parameter to all `Set-*` functions
* do something like this:

```pwsh
$result = Invoke-GHRestMethod @params
if ($PSBoundParameters.ContainsKey('PassThru'))
{
    $result
}
```

#### Requested Assignment

I'm just suggesting this idea, at this time. I'm not planning on implementing it.

**Comment by HowardWolosky** [comment]
Actually, for your sample code, you'd need it to be:

```powershell
$result = Invoke-GHRestMethod @params
if ($PassThru)
{
    return $result
}
```

The way you wrote it, you'd still behave using PassThru even if someone supplied `-PassThru:$false`.

**Comment by HowardWolosky** [comment]
This is an interesting idea.  I think I like it.  The main issue with it is that it would be a breaking change for users.  There are a lot of breaking changes lately, and I'm trying to be conscious about that.  We just added a breaking change with the `Remove-*` functions due to #171.  And #192 is deprecating the `Private` switch in favor of the `Visible` parameter.

I think that this could be done in a phased approach.

Phase 1: Add the `PassThru` switch and include the behavior above, but _still_ return the result with a warning indicating that in a future release, the result will only be returned if the PassThru switch is provided.
Phase 2: When that "future release" time is coming, check-in a change that removes the warning and only returns the result when the switch is provided.

Leaving this open for discussion to hear other people's thoughts on this Issue's suggestion in general, as well as the phased approach due to the breaking change.

**Comment by TylerLeonhardt** [comment]
Oh yeah sorry it should be:

```
$result = Invoke-GHRestMethod @params
if ($PassThru.IsPresent)
{
    return $result
}
```

**Comment by HowardWolosky** [comment]
Decided to just implement this anyway, since the next release is already going to be full of breaking changes.
