### ISSUE TITLE
Suggestion: Allow Automatic CI Triggering to be enabled by Adding a 'WaitForRunningBuilds` CI Step.

### ISSUE THREAD

**Issue by X-Guardian** [microsoft/PowerShellForGitHub#239]
#### Feature Idea Summary

Add a `WaitForRunningBuilds` step to the CI to allow automatic CI triggering to be enabled.

#### Feature Idea Additional Details

Currently the Azure Pipelines CI needs to be triggered manually as it runs integration tests that must be run serially and Azure Pipelines will run parallel jobs by default. It is not currently possible to disable parallel jobs, but a workaround as discussed in [Prevent parallel execution of the same build definition](https://developercommunity.visualstudio.com/idea/365730/prevent-parallel-execution-of-the-same-build-defin.html) is to add a `WaitForRunningBuilds` step to the CI.

#### Requested Assignment

- I'm just suggesting this idea, but don't want to implement it.

**Comment by HowardWolosky** [comment]
I don't see us ever enabling automatic CI triggering due to security issues.  Having it be manual was an intentional choice.  We need to vet the code changes going in to make sure that the changes aren't attempting to expose the `AccessToken` or do something malicious.

The `WaitForRunningBuilds` step though to allow for a queuing of serial CI builds is an interesting idea.  Will have to look into this further when I find some time.
