### ISSUE TITLE
Version 0.16.1 not in PowershellGallery

### ISSUE THREAD

**Issue by floh96** [microsoft/PowerShellForGitHub#350]
#### Issue Details

see https://www.powershellgallery.com/packages/PowerShellForGitHub version 0.16.1 is not available via PowershellGallery.
cc @HowardWolosky

**Comment by HowardWolosky** [comment]
This is an unfortunate known issue at the moment.  I'm only able to release _signed_ builds to PowerShellGallery, however the internal builds lost access to the necessary certificate for signing last year.  I'm continuing to try to get that certificate access restored so that builds and deployment from this repo can resume.

**Comment by HowardWolosky** [comment]
Good news!  I believe I have a workaround for my signing issues and will be able to release a signed version of 0.16.1 next week.  That workaround should also allow me to continue to release signed versions going forward as well, although it will have to be done manually as opposed to through the Release pipeline.

**Comment by HowardWolosky** [comment]
[`0.16.1` has been successfully signed and published to PowerShellGallery.](https://www.powershellgallery.com/packages/PowerShellForGitHub/0.16.1)  This proves out the new approach I need to use to sign releases moving forward.  It's now a manual approach (can't use an Azure Pipeline anymore), but it at least gets things unblocked for the project.
