### ISSUE TITLE
Support GitHub Enterprise

### ISSUE THREAD

**Issue by cliffchapmanrbx** [Microsoft/PowerShellForGitHub#98]
GitHub Enterprise supports nearly the same API for interacting, and it appears relatively straightforward to provide a way to override the otherwise hardcoded API URLs in `GitHubCore.ps1` to local GHE server environments.

Adding GHE support appears to be low hanging fruit. Is there any prior work done on this? Any pitfalls?

**Comment by cliffchapmanrbx** [comment]
I'm forking this to support our internal workflow around repo creation right now anyway, just want to see if it'd be worth the little more effort to push my changes upstream. I can't find the word 'enterprise' anywhere else is this repository (or issues, or docs...) so if it'd be accepted I can look into cleaning up the work I do for a PR.

**Comment by HowardWolosky** [comment]
Thanks @cliffchapmanrbx  -- While you're of course welcome to fork it for your own purposes, if it's really just because the endpoints are different, then I think everyone (both your users and those of this module) would be better off with a combined effort continuing on this one.

You're referring to [this API](https://developer.github.com/enterprise/2.5/v3/), right?

If it's just the endpoint that is different, it would seem like that could more easily be solved with a [new configuration property](https://github.com/PowerShell/PowerShellForGitHub/blob/master/CONTRIBUTING.md#adding-new-configuration-properties), possibly called `ApiEndpoint`, which just default to `https://api.github.com`, but can be re-configured to point to anything else.  `gitHubApiOrgsUrl` and `gitHubApiReposUrl` don't appear to be used anywhere, so they could just be deleted and not have any impact. Then that just leaves updating the logic in `Split-GitHubUri` to accomodate the new endpoint, which seems doable.

I'd love to hear more about what other issues you run into, as right now, that seems like the simplest path forward from my perspective.

Thanks for your interest!

**Comment by cliffchapmanrbx** [comment]
Good morning! 

That's more or less what I did, I ended up pulling out the parameters inside of `GitHubCore.ps1` and making any other references to 'github.com' pull from a configuration parameter, which I'm calling `GitHubBaseUrl`. So far it appears to be working on my local machine (and I believe you should be able to see my fork + branch [over here](https://github.com/cliffchapmanrbx/PowerShellForGitHub/tree/feature/add-github-enterprise-support). I'll be using it somewhat thoroughly throughout today and the rest of the week to confirm that it does everything I need to and should have time this weekend to open a proper PR from my personal account and get it cleaned up to your contribution standards.

The only thing that will probably be contentious is that I removed `ConvertFrom-Markdown` out of the module manifest. I'm running these commands in a mixed PS5/pwsh6 environment and the conflict was causing an issue. I understand that this repository has a strict requirement on backwards compatibility with PS4. That commit can be omitted for my actual PR. I'm not aware of a good workaround for this issue (can you even _do_ different manifests for different versions?) that would make the cmdlet available in environments where it wouldn't be overriding.

Expect a PR over the weekend to review on Monday. Thanks for the pointers!

**Comment by HowardWolosky** [comment]
Thanks @cliffchapmanrbx.  Based on your reply, I did some searching to better understand why you needed to disable `ConvertFrom-Markdown`, and now I understand that it was [added in PW6](https://github.com/PowerShell/PowerShell/commit/f8b3abaac7541d4ebf294ab8142222d06f65da6a).  So...it appears we should change the name of the one in this module to avoid the conflict.

I've opened #99 to track that issue so that you don't have to disable it to remain unblocked.

**Comment by HowardWolosky** [comment]
I should have `0.8.0` published with this change early next week.  I'm currently running into some odd issues with getting the code signed, which is a requirement for releasing an update, and need someone to help investigate that issue.

**Comment by HowardWolosky** [comment]
This has now been published to [PowerShellGallery](https://www.powershellgallery.com/packages/PowerShellForGitHub/0.8.0).  Thanks again for your contribution.

**Comment by Cellivar** [comment]
Happy to help! If I add anything else that might be worth it to submit I'll be back with more. Thanks again for your guidance.
